enabled_locales: ["en", "ja"]
user:
  max_name_size: 30
  maximum_age: 3
  maximum_email: 255
  minimum_password: 6
album:
  maxsize_title: 50

show_limit:
  show_5: 5
  show_10: 10
  show_20: 20
  show_30: 30
